// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbc0WkBM46odXzxAHLjZjN4ePIC4vTCI4',
    appId: '1:266994090766:android:1e27051386bb09f7894d5f',
    messagingSenderId: '266994090766',
    projectId: 'beytei-me',
    databaseURL: 'https://beytei-me-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beytei-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7cRZeGlqv1LqeCNfkeQUiasGmg8aStj4',
    appId: '1:266994090766:ios:1e61d51d5dcdb007894d5f',
    messagingSenderId: '266994090766',
    projectId: 'beytei-me',
    databaseURL: 'https://beytei-me-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beytei-me.firebasestorage.app',
    iosClientId: '266994090766-6ic3o5thaqej93dbsvohdbhl49vc40ad.apps.googleusercontent.com',
    iosBundleId: 'co.median.ios.wqwnby',
  );

}