workflows:
  ios-release-workflow:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        # تأكد من أن لديك مجموعة متغيرات باسم app_store_credentials في Codemagic
        # وتحتوي على مفتاح App Store Connect API Key الخاص بك
        - app_store_credentials
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: Build IPA for App Store
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $FLUTTER_BUILD_DIR/ios/xcarchive/Runner.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY

        # إرسال النسخة إلى TestFlight للاختبار
        submit_to_testflight: true

